In [1]:
# import necessary libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
# load the feature engineered training dataset
df = pd.read_csv("../data/fe_train.csv")

In [3]:
# check data head
df.head().T

,0,1,2,3,4
Age,58.000000,52.000000,56.000000,44.000000,58.000000
Sex,1.000000,1.000000,0.000000,0.000000,1.000000
Chest pain type,4.000000,1.000000,2.000000,3.000000,4.000000
BP,152.000000,125.000000,160.000000,134.000000,140.000000
Cholesterol,239.000000,325.000000,188.000000,229.000000,234.000000
FBS over 120,0.000000,0.000000,0.000000,0.000000,0.000000
EKG results,0.000000,2.000000,2.000000,2.000000,2.000000
Max HR,158.000000,171.000000,151.000000,150.000000,125.000000
Exercise angina,1.000000,0.000000,0.000000,0.000000,1.000000
ST depression,3.600000,0.000000,0.000000,1.000000,3.800000
Slope of ST,2.000000,1.000000,1.000000,2.000000,2.000000
Number of vessels fluro,2.000000,0.000000,0.000000,0.000000,3.000000
Thallium,7.000000,3.000000,3.000000,3.000000,3.000000
Heart Disease,1.000000,0.000000,0.000000,0.000000,1.000000
Any_vessel_disease,1.000000,0.000000,0.000000,0.000000,1.000000
Severe_vessel_disease,1.000000,0.000000,0.000000,0.000000,1.000000
Abnormal_thallium,1.000000,0.000000,0.000000,0.000000,0.000000
Exercise_ischemia_flag,1.000000,0.000000,0.000000,0.000000,1.000000
Heart_rate_reserve,-4.000000,3.000000,-13.000000,-26.000000,-37.000000
ST_depression_normalized,0.022785,0.000000,0.000000,0.006667,0.030400
ST_severity_level,3.000000,0.000000,0.000000,1.000000,3.000000
Global_heart_risk_index,4.000000,2.000000,2.000000,1.000000,5.000000
Metabolic_risk_score,1.000000,1.000000,1.000000,0.000000,1.000000
Age_squared,3364.000000,2704.000000,3136.000000,1936.000000,3364.000000
Abnormal_EKG_flag,0.000000,1.000000,1.000000,1.000000,1.000000
Typical_angina_flag,1.000000,0.000000,0.000000,1.000000,1.000000
Chest_pain_risk_score,3.000000,0.000000,1.000000,2.000000,3.000000
Low_HR_response_flag,0.000000,0.000000,0.000000,0.000000,1.000000
Exercise_risk_score,2.000000,0.000000,0.000000,1.000000,2.000000
Age_Sex_interaction,58.000000,52.000000,0.000000,0.000000,58.000000
BP_Chol_ratio,0.635983,0.384615,0.851064,0.585153,0.598291
High_BP_flag,1.000000,0.000000,1.000000,0.000000,1.000000
High_Chol_flag,0.000000,1.000000,0.000000,0.000000,0.000000
Age_group,2.000000,2.000000,2.000000,1.000000,2.000000

In [4]:
# check data info
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 630000 entries, 0 to 629999
Data columns (total 34 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   Age                       630000 non-null  int64
 1   Sex                       630000 non-null  int64
 2   Chest pain type           630000 non-null  int64
 3   BP                        630000 non-null  int64
 4   Cholesterol               630000 non-null  int64
 5   FBS over 120              630000 non-null  int64
 6   EKG results               630000 non-null  int64
 7   Max HR                    630000 non-null  int64
 8   Exercise angina           630000 non-null  int64
 9   ST depression             630000 non-null  float64
 10  Slope of ST               630000 non-null  int64
 11  Number of vessels fluro   630000 non-null  int64
 12  Thallium                  630000 non-null  int64
 13  Heart Disease             630000 non-null  int64
 14  Any_vessel_disease        630000 non-null  int64
 15  Severe_vessel_disease     630000 non-null  int64
 16  Abnormal_thallium         630000 non-null  int64
 17  Exercise_ischemia_flag    630000 non-null  int64
 18  Heart_rate_reserve        630000 non-null  int64
 19  ST_depression_normalized  630000 non-null  float64
 20  ST_severity_level         630000 non-null  int64
 21  Global_heart_risk_index   630000 non-null  int64
 22  Metabolic_risk_score      630000 non-null  int64
 23  Age_squared               630000 non-null  int64
 24  Abnormal_EKG_flag         630000 non-null  int64
 25  Typical_angina_flag       630000 non-null  int64
 26  Chest_pain_risk_score     630000 non-null  int64
 27  Low_HR_response_flag      630000 non-null  int64
 28  Exercise_risk_score       630000 non-null  int64
 29  Age_Sex_interaction       630000 non-null  int64
 30  BP_Chol_ratio             630000 non-null  float64
 31  High_BP_flag              630000 non-null  int64
 32  High_Chol_flag            630000 non-null  int64
 33  Age_group                 630000 non-null  int64
dtypes: float64(3), int64(31)
memory usage: 163.4 MB

In [5]:
# check data description
df.describe().T

,count,mean,std,min,25%,50%,75%,max
Age,630000.0,54.136706,8.256301,29.000000,48.000000,54.000000,60.000000,77.000000
Sex,630000.0,0.714735,0.451541,0.000000,0.000000,1.000000,1.000000,1.000000
Chest pain type,630000.0,3.312752,0.851615,1.000000,3.000000,4.000000,4.000000,4.000000
BP,630000.0,130.497433,14.975802,94.000000,120.000000,130.000000,140.000000,200.000000
Cholesterol,630000.0,245.011814,33.681581,126.000000,223.000000,243.000000,269.000000,564.000000
FBS over 120,630000.0,0.079987,0.271274,0.000000,0.000000,0.000000,0.000000,1.000000
EKG results,630000.0,0.981660,0.998783,0.000000,0.000000,0.000000,2.000000,2.000000
Max HR,630000.0,152.816763,19.112927,71.000000,142.000000,157.000000,166.000000,202.000000
Exercise angina,630000.0,0.273725,0.445870,0.000000,0.000000,0.000000,1.000000,1.000000
ST depression,630000.0,0.716028,0.948472,0.000000,0.000000,0.100000,1.400000,6.200000
Slope of ST,630000.0,1.455871,0.545192,1.000000,1.000000,1.000000,2.000000,3.000000
Number of vessels fluro,630000.0,0.451040,0.798549,0.000000,0.000000,0.000000,1.000000,3.000000
Thallium,630000.0,4.618873,1.950007,3.000000,3.000000,3.000000,7.000000,7.000000
Heart Disease,630000.0,0.448340,0.497324,0.000000,0.000000,0.000000,1.000000,1.000000
Any_vessel_disease,630000.0,0.292283,0.454812,0.000000,0.000000,0.000000,1.000000,1.000000
Severe_vessel_disease,630000.0,0.122476,0.327835,0.000000,0.000000,0.000000,0.000000,1.000000
Abnormal_thallium,630000.0,0.409070,0.491663,0.000000,0.000000,0.000000,1.000000,1.000000
Exercise_ischemia_flag,630000.0,0.142189,0.349244,0.000000,0.000000,0.000000,0.000000,1.000000
Heart_rate_reserve,630000.0,-13.046530,20.067037,-114.000000,-25.000000,-10.000000,1.000000,53.000000
ST_depression_normalized,630000.0,0.004973,0.006802,0.000000,0.000000,0.000538,0.009091,0.068182
ST_severity_level,630000.0,0.902386,1.035715,0.000000,0.000000,1.000000,2.000000,3.000000
Global_heart_risk_index,630000.0,2.305637,1.432834,0.000000,1.000000,2.000000,3.000000,7.000000
Metabolic_risk_score,630000.0,0.935481,0.734561,0.000000,0.000000,1.000000,1.000000,3.000000
Age_squared,630000.0,2998.949370,886.442549,841.000000,2304.000000,2916.000000,3600.000000,5929.000000
Abnormal_EKG_flag,630000.0,0.491879,0.499934,0.000000,0.000000,0.000000,1.000000,1.000000
Typical_angina_flag,630000.0,0.835646,0.370597,0.000000,1.000000,1.000000,1.000000,1.000000
Chest_pain_risk_score,630000.0,2.312752,0.851615,0.000000,2.000000,3.000000,3.000000,3.000000
Low_HR_response_flag,630000.0,0.244387,0.429724,0.000000,0.000000,0.000000,0.000000,1.000000
Exercise_risk_score,630000.0,0.773822,0.744135,0.000000,0.000000,1.000000,1.000000,2.000000
Age_Sex_interaction,630000.0,39.022944,25.604900,0.000000,0.000000,51.000000,58.000000,77.000000
BP_Chol_ratio,630000.0,0.542894,0.098779,0.195035,0.472441,0.530973,0.602410,1.342282
High_BP_flag,630000.0,0.317749,0.465602,0.000000,0.000000,0.000000,1.000000,1.000000
High_Chol_flag,630000.0,0.537744,0.498574,0.000000,0.000000,1.000000,1.000000,1.000000
Age_group,630000.0,1.886889,0.783742,0.000000,1.000000,2.000000,2.000000,3.000000

In [7]:
# check count of unique values in each column
df.nunique().sort_values()

Sex                            2
FBS over 120                   2
Severe_vessel_disease          2
Exercise angina                2
Heart Disease                  2
Any_vessel_disease             2
Exercise_ischemia_flag         2
Abnormal_thallium              2
Abnormal_EKG_flag              2
Typical_angina_flag            2
Low_HR_response_flag           2
High_BP_flag                   2
High_Chol_flag                 2
Thallium                       3
EKG results                    3
Exercise_risk_score            3
Slope of ST                    3
ST_severity_level              4
Chest pain type                4
Chest_pain_risk_score          4
Number of vessels fluro        4
Metabolic_risk_score           4
Age_group                      4
Global_heart_risk_index        8
Age                           42
Age_squared                   42
Age_Sex_interaction           43
BP                            66
ST depression                 66
Max HR                        93
Cholesterol                  150
Heart_rate_reserve           163
ST_depression_normalized    3021
BP_Chol_ratio               4409
dtype: int64

In [8]:
# print all unique values for columns with less than 5 unique values
for col in df.columns:
    if df[col].nunique() < 5:
        print(f"{col}: {df[col].unique()}")

Sex: [1 0]
Chest pain type: [4 1 2 3]
FBS over 120: [0 1]
EKG results: [0 2 1]
Exercise angina: [1 0]
Slope of ST: [2 1 3]
Number of vessels fluro: [2 0 3 1]
Thallium: [7 3 6]
Heart Disease: [1 0]
Any_vessel_disease: [1 0]
Severe_vessel_disease: [1 0]
Abnormal_thallium: [1 0]
Exercise_ischemia_flag: [1 0]
ST_severity_level: [3 0 1 2]
Metabolic_risk_score: [1 0 2 3]
Abnormal_EKG_flag: [0 1]
Typical_angina_flag: [1 0]
Chest_pain_risk_score: [3 0 1 2]
Low_HR_response_flag: [0 1]
Exercise_risk_score: [2 0 1]
High_BP_flag: [1 0]
High_Chol_flag: [0 1]
Age_group: [2 1 0 3]

In [9]:
# define numeric (continuous/discrete), categorical (binary/nominal/ordinal), and target columns

TARGET = ["Heart Disease"]

CATEGORICAL_BINARY = [
    "Sex",
    "FBS over 120",
    "Exercise angina",
    "Any_vessel_disease",
    "Severe_vessel_disease",
    "Abnormal_thallium",
    "Exercise_ischemia_flag",
    "Abnormal_EKG_flag",
    "Typical_angina_flag",
    "Low_HR_response_flag",
    "High_BP_flag",
    "High_Chol_flag"
]

CATEGORICAL_NOMINAL = [
    "Chest pain type",
    "EKG results",
    "Thallium"
]

CATEGORICAL_ORDINAL = [
    "Slope of ST",
    "ST_severity_level",
    "Chest_pain_risk_score",
    "Age_group"
]

NUMERIC_CONTINUOUS = [
    "Age",
    "BP",
    "Cholesterol",
    "Max HR",
    "ST depression",
    "Heart_rate_reserve",
    "ST_depression_normalized",
    "Age_squared",
    "BP_Chol_ratio",
    "Age_Sex_interaction"
]

NUMERIC_DISCRETE = [
    "Number of vessels fluro",
    "Metabolic_risk_score",
    "Exercise_risk_score"
]